### ISSUE TITLE
Wrong positioning of sdtc:functionCode inside performer tag of CareTeamMemberAct.

### ISSUE THREAD

**Issue by SubhashKonar** [HL7/cda-core-2.0#48]
[CCDA Validator](https://ett.healthit.gov/ett/#/validators/ccdar3#ccdaValdReport) if failing for the CCD with sdtc:functionCode tag inside performer tag.
![image](https://user-images.githubusercontent.com/64186900/117253806-3f9d1880-ae0d-11eb-88c8-8c26de5060f5.png)

Example for Care Teams XML  from [repo](https://github.com/HL7/C-CDA-Examples/tree/master/Guide%20Examples/Care%20Team%20Organizer_2.16.840.1.113883.10.20.22.4.500).
![image](https://user-images.githubusercontent.com/64186900/117254064-9276d000-ae0d-11eb-87da-43d27f3dc02a.png)

Care Teams Sample XML generated with MDHT library. 
![image](https://user-images.githubusercontent.com/64186900/117254235-c9e57c80-ae0d-11eb-9ed9-18c3818d94c6.png)

CCDA Validation is passing only when sdtc:functionCode is the first child of perfomer tag and fails if it is not the first child of performer tag.

The following CCD passes Validation.
![image](https://user-images.githubusercontent.com/64186900/117254462-0c0ebe00-ae0e-11eb-8be0-a28ca7e353c8.png)

The following CCD fails Validation.
![image](https://user-images.githubusercontent.com/64186900/117254235-c9e57c80-ae0d-11eb-9ed9-18c3818d94c6.png)

Can someone provide solution how to address the issue of positioning functionCode tag while using MDHT library ?

**Comment by benjaminflessner** [comment]
In the CDA schema, `sdtc:functionCode` precedes `assignedEntity` in the `Performer2` schema:

https://github.com/HL7/cda-core-2.0/blob/bd615ccb4d223a377921321e0f54ff3e2be762f4/schema/extensions/SDTC/infrastructure/cda/POCD_MT000040_SDTC.xsd#L1173-L1187

This follows the same pattern as the `Performer1` schema (where `functionCode` has been present since the release of CDA):

https://github.com/HL7/cda-core-2.0/blob/bd615ccb4d223a377921321e0f54ff3e2be762f4/schema/extensions/SDTC/infrastructure/cda/POCD_MT000040_SDTC.xsd#L1161-L1172

It sounds like the MDHT library is outputting (and expecting) the `sdtc:functionCode` in the wrong location. I would suggest following up with them. You're also welcome to come to a [C-CDA examples task force](https://confluence.hl7.org/display/SD/C-CDA+Examples+Task+Force) call for more help.
